/**
 * The channel token file (TECHNICAL-DESIGN §5.8, §4.1, SRV-07, SRV-08, FM-10).
 *
 * 32 random bytes written by the installer as 64 lowercase hex characters in
 * `~/.handoff/channel.token`, and read **at every connection attempt** rather than once at
 * startup, so that a token regenerated by the app's repair flow is picked up without
 * restarting the agent.
 *
 * Two rules that look like details and are not:
 *
 * - **A loose mode is a warning, never a refusal.** On POSIX a mode wider than `0600` means
 *   another user could read the token; the property that protects is the *app's*, not the
 *   server's, so the server says so once on stderr and connects anyway (§5.8). Refusing
 *   would deny the user their overlay to protect a secret that is not ours.
 * - **A missing or malformed file is `CHANNEL_AUTH_FAILED`**, the same state a rejected
 *   token produces (FM-10). There is nothing to send and no reason to invent one, and the
 *   fix the agent is told about — reinstall or repair from the app settings — is the same.
 *
 * The warning goes to stderr directly, for the reason `src/runbooks/reader.ts` gives at
 * length: a structured log record cannot carry a path without widening the allow-list of
 * `src/log.ts` enough to carry a spec value (R-19).
 */
import { readFileSync, statSync } from 'node:fs';

import type { EnvRecord } from '../config';

import { tokenPath } from './paths';

/** The shape `channel.v1.schema.json` requires of the token that travels in `hello`. */
export const TOKEN_PATTERN = /^[0-9a-f]{64}$/u;

/** The mode the installer writes (INST-07): readable and writable by the owner alone. */
export const TOKEN_MODE = 0o600;

/** Why the token could not be used. Every one of them means `CHANNEL_AUTH_FAILED`. */
export type TokenProblem = 'missing' | 'unreadable' | 'malformed';

export type TokenRead =
  | { readonly ok: true; readonly token: string }
  | { readonly ok: false; readonly problem: TokenProblem };

/** Where the warning about a loose mode goes. Injected so a test reads it. */
export type WarnSink = (line: string) => void;

const stderrWarn: WarnSink = (line) => {
  process.stderr.write(`${line}\n`);
};

export interface TokenFileOptions {
  readonly env?: EnvRecord;
  readonly platform?: NodeJS.Platform;
  readonly warn?: WarnSink;
  readonly readFile?: (path: string) => string;
  /** The permission bits of the file, or `undefined` when they cannot be read. */
  readonly mode?: (path: string) => number | undefined;
}

/** The `code` of a Node system error, when it has one. */
function errorCode(cause: unknown): string | undefined {
  if (typeof cause !== 'object' || cause === null) return undefined;
  const code = (cause as { code?: unknown }).code;
  return typeof code === 'string' ? code : undefined;
}

function statMode(path: string): number | undefined {
  try {
    return statSync(path).mode & 0o777;
  } catch {
    return undefined;
  }
}

/** Renders `0644`, the notation the fix sentence tells the user to type into `chmod`. */
function octal(mode: number): string {
  return `0${mode.toString(8).padStart(3, '0')}`;
}

/**
 * The token file, re-read on demand. The instance exists only to hold one bit of state:
 * whether the warning about the mode has already been written, so that a server retrying
 * every 30 s for an hour does not print it a hundred and twenty times.
 */
export class TokenFile {
  private readonly path: string;
  private readonly posix: boolean;
  private readonly warn: WarnSink;
  private readonly readFile: (path: string) => string;
  private readonly mode: (path: string) => number | undefined;
  private warned = false;

  constructor(options: TokenFileOptions = {}) {
    this.path = tokenPath(options.env);
    this.posix = (options.platform ?? process.platform) !== 'win32';
    this.warn = options.warn ?? stderrWarn;
    this.readFile = options.readFile ?? ((path) => readFileSync(path, 'utf8'));
    this.mode = options.mode ?? statMode;
  }

  /** The path the file is read from, for `doctor` (T-021) and for the tests. */
  get file(): string {
    return this.path;
  }

  /**
   * Reads the token. Trailing whitespace is tolerated because a text editor adds a newline
   * and the installer's file is otherwise indistinguishable; anything else that is not 64
   * lowercase hex characters is `malformed`, since the app would refuse it as a framing
   * violation and never get to say `auth_failed`.
   */
  read(): TokenRead {
    let text: string;
    try {
      text = this.readFile(this.path);
    } catch (cause) {
      const code = errorCode(cause);
      const missing = code === 'ENOENT' || code === 'ENOTDIR';
      return { ok: false, problem: missing ? 'missing' : 'unreadable' };
    }

    const token = text.trim();
    if (!TOKEN_PATTERN.test(token)) return { ok: false, problem: 'malformed' };

    this.checkMode();
    return { ok: true, token };
  }

  /** One warning per process when the mode is wider than `0600` (§5.8). Never on Windows. */
  private checkMode(): void {
    if (!this.posix || this.warned) return;
    const mode = this.mode(this.path);
    if (mode === undefined || (mode & ~TOKEN_MODE & 0o777) === 0) return;
    this.warned = true;
    this.warn(
      `handoff-mcp: ${this.path} has mode ${octal(mode)}, wider than ${octal(TOKEN_MODE)}: ` +
        `other users of this machine can read the channel token. Fix it with ` +
        `chmod 600 ${this.path}. Connecting anyway.`,
    );
  }
}
